# Generated by Django 3.1.4 on 2021-01-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maruzalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maruza_nomi', models.CharField(max_length=50)),
                ('muallif', models.CharField(max_length=50)),
                ('maruza_audio', models.FileField(upload_to='audio-maruzalar')),
            ],
        ),
    ]
