# Generated by Django 3.1.4 on 2021-01-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_maruzalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars_nomi', models.CharField(max_length=50)),
                ('muallif', models.CharField(max_length=30)),
                ('audio', models.FileField(upload_to='audio-darsliklar')),
                ('qaysi_darsga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mavzu')),
            ],
        ),
    ]
