# Generated by Django 3.1.4 on 2021-01-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_dars_mavzu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dars',
            old_name='qaysi_darsga',
            new_name='qaysi_mavzu',
        ),
    ]
