# Generated by Django 3.1.4 on 2021-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_auto_20210120_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namozvaqti',
            name='asr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='namozvaqti',
            name='peshin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='namozvaqti',
            name='quyosh',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='namozvaqti',
            name='shom',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='namozvaqti',
            name='tong',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='namozvaqti',
            name='xufton',
            field=models.CharField(max_length=10),
        ),
    ]
